import type { Metadata } from "next";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={styles.body}>
        {children}
      </body>
    </html>
  );
}
